/**
 * component-categories.ts
 *
 * Maps every sherpa-* custom element tag name to its role category,
 * numeric composition tier, and atomic-design string tier.
 * Roles + tiers are defined in docs/COMPONENT-CATEGORIES.md.
 * String tiers are defined in docs/COMPONENT-TIER-MAPPING.md.
 */

import type { ComponentTier } from './types.js';

export type ComponentCategory =
  | 'shell'
  | 'nav'
  | 'container'
  | 'overlay'
  | 'content'
  | 'control'
  | 'input'
  | 'display'
  | 'feedback'
  | 'media'
  | 'data'
  | 'utility'
  | 'ai';

export const COMPONENT_CATEGORIES: Record<string, ComponentCategory> = Object.freeze({
  'sherpa-accordion': 'container',
  'sherpa-barchart': 'media',
  'sherpa-breadcrumbs': 'control',
  'sherpa-app-shell': 'shell',
  'sherpa-app-header': 'shell',
  'sherpa-button': 'control',
  'sherpa-calendar': 'input',
  'sherpa-callout': 'feedback',
  'sherpa-chart-legend': 'media',
  'sherpa-chat-message': 'ai',
  'sherpa-code-block': 'utility',
  'sherpa-container': 'container',
  'sherpa-container-footer': 'container',
  'sherpa-container-group': 'container',
  'sherpa-container-header': 'container',
  'sherpa-data-grid': 'data',
  'sherpa-container-overlay': 'overlay',
  'sherpa-dialog': 'overlay',
  'sherpa-donut-chart': 'media',
  'sherpa-empty-state': 'feedback',
  'sherpa-file-upload': 'input',
  'sherpa-quick-filter': 'control',
  'sherpa-quick-filter-toolbar': 'data',
  'sherpa-gauge-chart': 'media',
  'sherpa-icon': 'media',
  'sherpa-select-checkbox': 'input',
  'sherpa-select-group':         'input',
  'sherpa-input-date': 'input',
  'sherpa-input-date-range': 'input',
  'sherpa-input-number': 'input',
  'sherpa-input-password': 'input',
  'sherpa-select-radio': 'input',
  'sherpa-input-search': 'input',
  'sherpa-input-select': 'input',
  'sherpa-input-tag': 'input',
  'sherpa-input-text': 'input',
  'sherpa-input-time': 'input',
  'sherpa-key-value-list': 'content',
  'sherpa-layout-grid': 'shell',
  'sherpa-line-chart': 'media',
  'sherpa-list': 'content',
  'sherpa-tree': 'content',
  'sherpa-list-item': 'content',
  'sherpa-loader': 'feedback',
  'sherpa-overlay-item': 'overlay',
  'sherpa-message': 'feedback',
  'sherpa-metric': 'display',
  'sherpa-nav': 'shell',
  'sherpa-nav-item': 'nav',
  'sherpa-nav-section': 'nav',
  'sherpa-node': 'content',
  'sherpa-node-canvas': 'data',
  'sherpa-node-header': 'content',
  'sherpa-node-row': 'content',
  'sherpa-node-socket': 'content',
  'sherpa-pagination': 'control',
  'sherpa-panel': 'container',
  'sherpa-product-bar': 'shell',
  'sherpa-product-bar-v2': 'shell',
  'sherpa-progress-bar': 'display',
  'sherpa-progress-tracker': 'content',
  'sherpa-prompt-composer': 'ai',
  'sherpa-proposal-op': 'ai',
  'sherpa-proposal-preview': 'ai',
  'sherpa-scheduler': 'data',
  'sherpa-section-header': 'content',
  'sherpa-slider': 'control',
  'sherpa-sparkline': 'media',
  'sherpa-stepper': 'content',
  'sherpa-switch': 'control',
  'sherpa-tabs': 'content',
  'sherpa-tag': 'control',
  'sherpa-toast': 'feedback',
  'sherpa-toolbar': 'content',
  'sherpa-tooltip': 'overlay',
  'sherpa-transfer-list': 'data',
  'sherpa-view-header': 'shell',
});

export const ROLE_TIERS: Record<ComponentCategory, number> = Object.freeze({
  shell: 1,
  nav: 1,
  container: 2,
  overlay: 2,
  content: 3,
  ai: 3,
  control: 4,
  input: 4,
  display: 4,
  feedback: 4,
  media: 4,
  data: 4,
  utility: 5,
});

export const COMPONENT_TIERS: Record<string, number> = Object.freeze({
  'sherpa-app-shell': 1,
  'sherpa-app-header': 1,
  'sherpa-accordion': 2,
  'sherpa-barchart': 4,
  'sherpa-breadcrumbs': 4,
  'sherpa-button': 4,
  'sherpa-calendar': 5,
  'sherpa-callout': 4,
  'sherpa-chart-legend': 4,
  'sherpa-chat-message': 3,
  'sherpa-code-block': 5,
  'sherpa-container': 2,
  'sherpa-container-footer': 2,
  'sherpa-container-group': 2,
  'sherpa-container-header': 2,
  'sherpa-data-grid': 4,
  'sherpa-container-overlay': 2,
  'sherpa-dialog': 2,
  'sherpa-donut-chart': 4,
  'sherpa-empty-state': 4,
  'sherpa-file-upload': 4,
  'sherpa-quick-filter': 4,
  'sherpa-quick-filter-toolbar': 4,
  'sherpa-gauge-chart': 4,
  'sherpa-icon': 4,
  'sherpa-select-checkbox': 4,
  'sherpa-select-group':         4,
  'sherpa-input-date': 4,
  'sherpa-input-date-range': 4,
  'sherpa-input-number': 4,
  'sherpa-input-password': 4,
  'sherpa-select-radio': 4,
  'sherpa-input-search': 4,
  'sherpa-input-select': 4,
  'sherpa-input-tag': 4,
  'sherpa-input-text': 4,
  'sherpa-input-time': 4,
  'sherpa-key-value-list': 3,
  'sherpa-layout-grid': 1,
  'sherpa-line-chart': 4,
  'sherpa-list': 3,
  'sherpa-tree': 3,
  'sherpa-list-item': 3,
  'sherpa-loader': 4,
  'sherpa-overlay-item': 2,
  'sherpa-message': 4,
  'sherpa-metric': 4,
  'sherpa-nav': 1,
  'sherpa-nav-item': 1,
  'sherpa-nav-section': 1,
  'sherpa-node': 3,
  'sherpa-node-canvas': 3,
  'sherpa-node-header': 3,
  'sherpa-node-row': 3,
  'sherpa-node-socket': 3,
  'sherpa-pagination': 4,
  'sherpa-panel': 2,
  'sherpa-product-bar': 1,
  'sherpa-product-bar-v2': 1,
  'sherpa-progress-bar': 4,
  'sherpa-progress-tracker': 3,
  'sherpa-prompt-composer': 3,
  'sherpa-proposal-op': 3,
  'sherpa-proposal-preview': 3,
  'sherpa-scheduler': 4,
  'sherpa-section-header': 3,
  'sherpa-slider': 4,
  'sherpa-sparkline': 4,
  'sherpa-stepper': 3,
  'sherpa-switch': 4,
  'sherpa-tabs': 3,
  'sherpa-tag': 4,
  'sherpa-toast': 4,
  'sherpa-toolbar': 3,
  'sherpa-tooltip': 2,
  'sherpa-transfer-list': 4,
  'sherpa-view-header': 1,
});

/** Look up the role category for a given tag name. Returns null if unknown. */
export function getCategory(tagName: string | null | undefined): ComponentCategory | null {
  if (!tagName) return null;
  return (COMPONENT_CATEGORIES[tagName.toLowerCase()] as ComponentCategory) || null;
}

/** Look up the composition tier (1–5) for a given tag name. Null if unknown. */
export function getTier(tagName: string | null | undefined): number | null {
  if (!tagName) return null;
  return COMPONENT_TIERS[tagName.toLowerCase()] ?? null;
}

/** Atomic-design string tier for each component. See docs/COMPONENT-TIER-MAPPING.md. */
export const COMPONENT_STRING_TIERS: Record<string, ComponentTier> = Object.freeze({
  // structure — layout/surface wrappers with no domain logic
  'sherpa-app-shell':        'structure',
  'sherpa-app-header':       'structure',
  'sherpa-layout-grid':      'structure',
  'sherpa-container':        'structure',
  'sherpa-container-group':  'structure',
  'sherpa-panel':            'structure',
  'sherpa-accordion':        'structure',
  'sherpa-node-canvas':      'structure',
  // organism — complex, self-contained sections
  'sherpa-nav':              'organism',
  'sherpa-product-bar':      'organism',
  'sherpa-product-bar-v2':   'organism',
  'sherpa-view-header':      'organism',
  'sherpa-container-header': 'organism',
  'sherpa-container-footer': 'organism',
  'sherpa-dialog':           'organism',
  'sherpa-data-grid':        'organism',
  'sherpa-quick-filter':          'molecule',
  'sherpa-quick-filter-toolbar':  'organism',
  'sherpa-calendar':         'organism',
  'sherpa-transfer-list':    'organism',
  'sherpa-scheduler':        'organism',
  'sherpa-list':             'organism',
  'sherpa-tree':             'organism',
  'sherpa-toolbar':          'organism',
  'sherpa-pagination':       'organism',
  'sherpa-metric':           'organism',
  'sherpa-barchart':         'organism',
  'sherpa-line-chart':       'organism',
  'sherpa-donut-chart':      'organism',
  'sherpa-gauge-chart':      'organism',
  'sherpa-prompt-composer':  'organism',
  'sherpa-proposal-op':      'organism',
  'sherpa-proposal-preview': 'organism',
  'sherpa-code-block':       'organism',
  // molecule — composed of atoms; serves one workflow step
  'sherpa-container-overlay':     'molecule',
  'sherpa-overlay-item':          'molecule',
  'sherpa-list-item':             'molecule',
  'sherpa-key-value-list':        'molecule',
  'sherpa-tabs':                  'molecule',
  'sherpa-stepper':               'molecule',
  'sherpa-progress-tracker':      'molecule',
  'sherpa-breadcrumbs':           'molecule',
  'sherpa-section-header':        'molecule',
  'sherpa-nav-section':           'molecule',
  'sherpa-nav-item':              'molecule',
  'sherpa-node':                  'molecule',
  'sherpa-node-row':              'molecule',
  'sherpa-chart-legend':          'molecule',
  'sherpa-chat-message':          'molecule',
  'sherpa-empty-state':           'molecule',
  'sherpa-input-text':            'molecule',
  'sherpa-input-number':          'molecule',
  'sherpa-input-password':        'molecule',
  'sherpa-input-search':          'molecule',
  'sherpa-input-select':          'molecule',
  'sherpa-input-time':            'molecule',
  'sherpa-select-group':          'molecule',
  'sherpa-input-date':            'molecule',
  'sherpa-input-date-range':      'molecule',
  'sherpa-input-tag':             'molecule',
  'sherpa-file-upload':           'molecule',
  // atom — single-purpose primitives
  'sherpa-button':          'atom',
  'sherpa-icon':            'atom',
  'sherpa-tag':             'atom',
  'sherpa-switch':          'atom',
  'sherpa-slider':          'atom',
  'sherpa-tooltip':         'atom',
  'sherpa-loader':          'atom',
  'sherpa-progress-bar':    'atom',
  'sherpa-sparkline':       'atom',
  'sherpa-message':         'atom',
  'sherpa-callout':         'atom',
  'sherpa-toast':           'atom',
  'sherpa-select-checkbox': 'atom',
  'sherpa-select-radio':    'atom',
  'sherpa-node-header':     'atom',
  'sherpa-node-socket':     'atom',
});

/** Look up the atomic-design string tier for a given tag name. Null if unknown. */
export function getStringTier(tagName: string | null | undefined): ComponentTier | null {
  if (!tagName) return null;
  return COMPONENT_STRING_TIERS[tagName.toLowerCase()] ?? null;
}
