/**
 * component-categories.ts
 * GENERATED by scripts/extract-component-schemas.js — do not edit by hand.
 *
 * Maps every sherpa-* custom element tag name to its role category and
 * composition tier. Roles + tiers are defined in docs/COMPONENT-CATEGORIES.md.
 */

export type ComponentCategory =
  | 'shell'
  | 'nav'
  | 'container'
  | 'overlay'
  | 'content'
  | 'control'
  | 'input'
  | 'display'
  | 'feedback'
  | 'media'
  | 'data'
  | 'utility'
  | 'ai';

export const COMPONENT_CATEGORIES: Record<string, ComponentCategory> = Object.freeze({
  'sherpa-accordion': 'container',
  'sherpa-barchart': 'media',
  'sherpa-breadcrumbs': 'control',
  'sherpa-button': 'control',
  'sherpa-calendar': 'utility',
  'sherpa-callout': 'feedback',
  'sherpa-chart-legend': 'media',
  'sherpa-chat-message': 'ai',
  'sherpa-code-block': 'utility',
  'sherpa-container': 'container',
  'sherpa-container-footer': 'container',
  'sherpa-container-group': 'container',
  'sherpa-container-header': 'container',
  'sherpa-data-grid': 'data',
  'sherpa-date-time-picker': 'input',
  'sherpa-dialog': 'overlay',
  'sherpa-donut-chart': 'media',
  'sherpa-empty-state': 'feedback',
  'sherpa-file-upload': 'input',
  'sherpa-filter-bar': 'data',
  'sherpa-gauge-chart': 'media',
  'sherpa-icon': 'media',
  'sherpa-input-checkbox': 'input',
  'sherpa-input-checkbox-group': 'input',
  'sherpa-input-date': 'input',
  'sherpa-input-date-range': 'input',
  'sherpa-input-number': 'input',
  'sherpa-input-password': 'input',
  'sherpa-input-radio': 'input',
  'sherpa-input-radio-group': 'input',
  'sherpa-input-search': 'input',
  'sherpa-input-select': 'input',
  'sherpa-input-tag': 'input',
  'sherpa-input-text': 'input',
  'sherpa-input-time': 'input',
  'sherpa-key-value-list': 'content',
  'sherpa-layout-grid': 'shell',
  'sherpa-layout-view': 'shell',
  'sherpa-line-chart': 'media',
  'sherpa-list': 'content',
  'sherpa-list-item': 'content',
  'sherpa-loader': 'feedback',
  'sherpa-menu': 'overlay',
  'sherpa-menu-item': 'overlay',
  'sherpa-message': 'feedback',
  'sherpa-metric': 'display',
  'sherpa-nav': 'shell',
  'sherpa-nav-item': 'nav',
  'sherpa-nav-section': 'nav',
  'sherpa-node': 'content',
  'sherpa-node-canvas': 'data',
  'sherpa-node-header': 'content',
  'sherpa-node-row': 'content',
  'sherpa-node-socket': 'content',
  'sherpa-pagination': 'control',
  'sherpa-panel': 'container',
  'sherpa-popover': 'overlay',
  'sherpa-product-bar': 'shell',
  'sherpa-product-bar-v2': 'shell',
  'sherpa-progress-bar': 'display',
  'sherpa-progress-tracker': 'content',
  'sherpa-prompt-composer': 'ai',
  'sherpa-proposal-op': 'ai',
  'sherpa-proposal-preview': 'ai',
  'sherpa-scheduler': 'data',
  'sherpa-section-header': 'content',
  'sherpa-slider': 'control',
  'sherpa-sparkline': 'media',
  'sherpa-stepper': 'content',
  'sherpa-switch': 'control',
  'sherpa-tabs': 'content',
  'sherpa-tag': 'control',
  'sherpa-toast': 'feedback',
  'sherpa-toolbar': 'content',
  'sherpa-tooltip': 'overlay',
  'sherpa-transfer-list': 'data',
  'sherpa-view-header': 'shell',
});

export const ROLE_TIERS: Record<ComponentCategory, number> = Object.freeze({
  shell: 1,
  nav: 1,
  container: 2,
  overlay: 2,
  content: 3,
  ai: 3,
  control: 4,
  input: 4,
  display: 4,
  feedback: 4,
  media: 4,
  data: 4,
  utility: 5,
});

export const COMPONENT_TIERS: Record<string, number> = Object.freeze({
  'sherpa-accordion': 2,
  'sherpa-barchart': 4,
  'sherpa-breadcrumbs': 4,
  'sherpa-button': 4,
  'sherpa-calendar': 5,
  'sherpa-callout': 4,
  'sherpa-chart-legend': 4,
  'sherpa-chat-message': 3,
  'sherpa-code-block': 5,
  'sherpa-container': 2,
  'sherpa-container-footer': 2,
  'sherpa-container-group': 2,
  'sherpa-container-header': 2,
  'sherpa-data-grid': 4,
  'sherpa-date-time-picker': 4,
  'sherpa-dialog': 2,
  'sherpa-donut-chart': 4,
  'sherpa-empty-state': 4,
  'sherpa-file-upload': 4,
  'sherpa-filter-bar': 4,
  'sherpa-gauge-chart': 4,
  'sherpa-icon': 4,
  'sherpa-input-checkbox': 4,
  'sherpa-input-checkbox-group': 4,
  'sherpa-input-date': 4,
  'sherpa-input-date-range': 4,
  'sherpa-input-number': 4,
  'sherpa-input-password': 4,
  'sherpa-input-radio': 4,
  'sherpa-input-radio-group': 4,
  'sherpa-input-search': 4,
  'sherpa-input-select': 4,
  'sherpa-input-tag': 4,
  'sherpa-input-text': 4,
  'sherpa-input-time': 4,
  'sherpa-key-value-list': 3,
  'sherpa-layout-grid': 1,
  'sherpa-layout-view': 1,
  'sherpa-line-chart': 4,
  'sherpa-list': 3,
  'sherpa-list-item': 3,
  'sherpa-loader': 4,
  'sherpa-menu': 2,
  'sherpa-menu-item': 2,
  'sherpa-message': 4,
  'sherpa-metric': 4,
  'sherpa-nav': 1,
  'sherpa-nav-item': 1,
  'sherpa-nav-section': 1,
  'sherpa-node': 3,
  'sherpa-node-canvas': 3,
  'sherpa-node-header': 3,
  'sherpa-node-row': 3,
  'sherpa-node-socket': 3,
  'sherpa-pagination': 4,
  'sherpa-panel': 2,
  'sherpa-popover': 2,
  'sherpa-product-bar': 1,
  'sherpa-product-bar-v2': 1,
  'sherpa-progress-bar': 4,
  'sherpa-progress-tracker': 3,
  'sherpa-prompt-composer': 3,
  'sherpa-proposal-op': 3,
  'sherpa-proposal-preview': 3,
  'sherpa-scheduler': 4,
  'sherpa-section-header': 3,
  'sherpa-slider': 4,
  'sherpa-sparkline': 4,
  'sherpa-stepper': 3,
  'sherpa-switch': 4,
  'sherpa-tabs': 3,
  'sherpa-tag': 4,
  'sherpa-toast': 4,
  'sherpa-toolbar': 3,
  'sherpa-tooltip': 2,
  'sherpa-transfer-list': 4,
  'sherpa-view-header': 1,
});

/** Look up the role category for a given tag name. Returns null if unknown. */
export function getCategory(tagName: string | null | undefined): ComponentCategory | null {
  if (!tagName) return null;
  return (COMPONENT_CATEGORIES[tagName.toLowerCase()] as ComponentCategory) || null;
}

/** Look up the composition tier (1–5) for a given tag name. Null if unknown. */
export function getTier(tagName: string | null | undefined): number | null {
  if (!tagName) return null;
  return COMPONENT_TIERS[tagName.toLowerCase()] ?? null;
}
