#!/usr/bin/env node
/**
 * Build `src/core/icon-paths.ts` from the SVGs in `src/icons/`.
 *
 * Each entry carries the drawing's inner markup plus its INK bbox, so a viewBox
 * can be fitted to the art itself. An icon's 14x14 frame pads each drawing
 * differently — `triangle-down` inks 7x4.375 of its 14 box — so the frame
 * cannot size the art.
 *
 * The bbox needs a real SVG engine, so the drawings run through headless
 * Chromium once at build time. Nothing measures at runtime.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { chromium } from '@playwright/test';

const DIR = 'src/icons';
const OUT = 'src/core/ui/icon-paths.ts';

const files = readdirSync(DIR).filter((f) => f.endsWith('.svg')).sort();
if (files.length === 0) {
  console.error(`generate-icons: no .svg files in ${DIR}/`);
  process.exit(1);
}

const icons = [];
const skipped = [];
for (const file of files) {
  const src = readFileSync(join(DIR, file), 'utf8');
  const viewBox = /viewBox="([^"]+)"/.exec(src)?.[1];
  // The BODY, not a joined path list: a polychrome icon's paths carry different
  // fills, and `status-ok` is a green disc with a white tick knocked out of it.
  const body = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(src)?.[1]?.trim();
  if (!viewBox || !body) { skipped.push(`${file} (no viewBox or body)`); continue; }
  icons.push({ name: basename(file, '.svg'), viewBox, body });
}

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent('<div id="probe"></div>');
const measured = await page.evaluate((list) => {
  const host = document.getElementById('probe');
  const NS = 'http://www.w3.org/2000/svg';
  return list.map(({ name, viewBox, body }) => {
    const svg = document.createElementNS(NS, 'svg');
    svg.setAttribute('viewBox', viewBox);
    // The body is markup, so it must be parsed IN the SVG namespace — an
    // innerHTML on an SVG element does that; on an HTML one it would not.
    svg.innerHTML = body;
    host.appendChild(svg);
    // The union of every shape, which is the drawing's true extent.
    const b = svg.getBBox();
    host.replaceChildren();
    const r = (n) => Math.round(n * 1000) / 1000;
    return { name, ink: [r(b.x), r(b.y), r(b.width), r(b.height)], empty: b.width === 0 || b.height === 0 };
  });
}, icons);
await browser.close();

const inkByName = new Map(measured.map((m) => [m.name, m]));
const empty = measured.filter((m) => m.empty).map((m) => m.name);

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const rows = icons
  .map((i) => {
    const { ink } = inkByName.get(i.name);
    const body = esc(i.body.replace(/\s*\n\s*/g, ''));
    return `  '${i.name}': { body: \`${body}\`, ink: [${ink.join(', ')}] },`;
  })
  .join('\n');

writeFileSync(OUT, `// GENERATED by scripts/generate-icons.mjs from src/icons/ — do not edit.
// Each icon carries its drawing and the INK bbox [x, y, width, height] of that
// drawing, which is what a fitted viewBox needs. An icon's own frame pads each
// drawing differently, so the frame cannot size the art.

export interface IconArt {
  /** The SVG body — one or more shapes, with their own fills preserved. */
  readonly body: string;
  /** The drawing's bounding box: [x, y, width, height], in viewBox units. */
  readonly ink: readonly [number, number, number, number];
}

export const ICON_PATHS: Readonly<Record<string, IconArt>> = {
${rows}
};

/** Every icon name, for the tests and the catalog. */
export const ICON_NAMES: readonly string[] = Object.keys(ICON_PATHS);
`);

console.log(`generate-icons: ${icons.length} icons → ${OUT}`);
if (skipped.length) console.log(`  skipped: ${skipped.join(', ')}`);
if (empty.length) console.log(`  EMPTY (drew nothing): ${empty.join(', ')}`);
