#!/usr/bin/env node
/**
 * Rewrites each spec's `$extensions.sherpa` variantAxes/booleanProps from a live
 * Figma snapshot. Nothing else is touched; textProps is not compared.
 *
 *   node scripts/resync-figma.mjs <live-figma.json> [--dry|--check]
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const C = join(ROOT, 'src', 'components');
const args = process.argv.slice(2);
const DRY = args.includes('--dry');
const CHECK = args.includes('--check'); // report drift, exit non-zero, write nothing
const snapPath = args.find((a) => !a.startsWith('--'));
if (!snapPath) { console.error('usage: resync-figma.mjs <live-figma.json> [--dry|--check]'); process.exit(1); }
const live = JSON.parse(readFileSync(snapPath, 'utf8'));

// Order-independent comparison keys.
const norm = (a) => [...(a || [])].sort();
const axesKey = (ax) => (ax || []).map((a) => `${a.name}[${[...(a.values || [])].sort().join(',')}]`).sort().join(' ');

let synced = 0, unchanged = 0, noMatch = 0;
const changes = [];
const drift = [];

for (const n of readdirSync(C)) {
  const p = join(C, n, `${n}.component.json`);
  if (!existsSync(p)) continue;
  const spec = JSON.parse(readFileSync(p, 'utf8'));
  const ext = (spec.$extensions && spec.$extensions.sherpa) || {};
  const figmaName = ext.figmaName;
  if (!figmaName) { noMatch++; continue; }
  const L = live[figmaName];
  if (!L) { noMatch++; continue; }

  if (CHECK) {
    const issues = [];
    if (axesKey(ext.variantAxes) !== axesKey(L.variantAxes)) issues.push(`axes: spec[${axesKey(ext.variantAxes) || '—'}] vs live[${axesKey(L.variantAxes) || '—'}]`);
    if (norm(ext.booleanProps).join() !== norm(L.booleanProps).join()) issues.push(`bool: spec[${norm(ext.booleanProps).join()}] vs live[${norm(L.booleanProps).join()}]`);
    if (issues.length) { drift.push({ name: n, figmaName, issues }); }
    continue;
  }

  const before = JSON.stringify({ variantAxes: ext.variantAxes ?? null, booleanProps: ext.booleanProps ?? [] });

  // Only the live-derived fields; every other authored key survives.
  const next = { ...ext };
  next.figmaName = figmaName;
  if (L.variantAxes && L.variantAxes.length) next.variantAxes = L.variantAxes.map((a) => ({ name: a.name, values: [...a.values] }));
  else delete next.variantAxes;
  if (L.booleanProps && L.booleanProps.length) next.booleanProps = [...L.booleanProps];
  else delete next.booleanProps;

  const after = JSON.stringify({ variantAxes: next.variantAxes ?? null, booleanProps: next.booleanProps ?? [] });
  if (before === after) { unchanged++; continue; }

  spec.$extensions = { ...(spec.$extensions || {}), sherpa: next };
  // Its $comment rides along: without the "GENERATED by" line the generator
  // stops owning the spec and `--all` silently skips it.
  if (!DRY) writeFileSync(p, `${JSON.stringify(spec, null, 2)}\n`);
  synced++;
  changes.push(`${n} (${figmaName})`);
}

if (CHECK) {
  const aligned = Object.keys(live).length;
  if (drift.length === 0) {
    console.log('✅ all defs agree with live Figma (axes / booleanProps / textProps).');
    process.exit(0);
  }
  console.log(`⚠️  ${drift.length} def(s) DRIFT from live Figma:\n`);
  for (const d of drift) { console.log(`  ${d.name} (${d.figmaName})`); d.issues.forEach((i) => console.log(`      ${i}`)); }
  console.log(`\nRun without --check to re-sync, or update the defs by hand.`);
  process.exit(1);
}
console.log(`${DRY ? '[dry] ' : ''}synced ${synced}, unchanged ${unchanged}, no live match ${noMatch}`);
if (changes.length) { console.log('\nRe-synced:'); changes.forEach((c) => console.log('  ✎ ' + c)); }
